#ifndef _ALTERA_HPS_0_H_
#define _ALTERA_HPS_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file '../soc_system.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps_0' and devices
 * connected to the following masters:
 *   h2f_axi_master
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'DMA', class 'altera_avalon_dma'
 * The macros are prefixed with 'DMA_'.
 * The prefix is the slave descriptor.
 */
#define DMA_COMPONENT_TYPE altera_avalon_dma
#define DMA_COMPONENT_NAME DMA
#define DMA_BASE 0x0
#define DMA_SPAN 32
#define DMA_END 0x1f
#define DMA_IRQ 0
#define DMA_ALLOW_BYTE_TRANSACTIONS 1
#define DMA_ALLOW_DOUBLEWORD_TRANSACTIONS 1
#define DMA_ALLOW_HW_TRANSACTIONS 1
#define DMA_ALLOW_QUADWORD_TRANSACTIONS 1
#define DMA_ALLOW_WORD_TRANSACTIONS 1
#define DMA_LENGTHWIDTH 16
#define DMA_MAX_BURST_SIZE 128

/*
 * Macros for device 'BUFFER', class 'altera_avalon_onchip_memory2'
 * Path to the device is from the master group 'DMA_read_master'.
 * The macros are prefixed with 'DMA_READ_MASTER_BUFFER_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define DMA_READ_MASTER_BUFFER_COMPONENT_TYPE altera_avalon_onchip_memory2
#define DMA_READ_MASTER_BUFFER_COMPONENT_NAME BUFFER
#define DMA_READ_MASTER_BUFFER_BASE 0x20000
#define DMA_READ_MASTER_BUFFER_SPAN 131072
#define DMA_READ_MASTER_BUFFER_END 0x3ffff
#define DMA_READ_MASTER_BUFFER_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define DMA_READ_MASTER_BUFFER_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define DMA_READ_MASTER_BUFFER_CONTENTS_INFO ""
#define DMA_READ_MASTER_BUFFER_DUAL_PORT 0
#define DMA_READ_MASTER_BUFFER_GUI_RAM_BLOCK_TYPE AUTO
#define DMA_READ_MASTER_BUFFER_INIT_CONTENTS_FILE soc_system_BUFFER
#define DMA_READ_MASTER_BUFFER_INIT_MEM_CONTENT 1
#define DMA_READ_MASTER_BUFFER_INSTANCE_ID NONE
#define DMA_READ_MASTER_BUFFER_NON_DEFAULT_INIT_FILE_ENABLED 0
#define DMA_READ_MASTER_BUFFER_RAM_BLOCK_TYPE AUTO
#define DMA_READ_MASTER_BUFFER_READ_DURING_WRITE_MODE DONT_CARE
#define DMA_READ_MASTER_BUFFER_SINGLE_CLOCK_OP 0
#define DMA_READ_MASTER_BUFFER_SIZE_MULTIPLE 1
#define DMA_READ_MASTER_BUFFER_SIZE_VALUE 131072
#define DMA_READ_MASTER_BUFFER_WRITABLE 1
#define DMA_READ_MASTER_BUFFER_MEMORY_INFO_DAT_SYM_INSTALL_DIR SIM_DIR
#define DMA_READ_MASTER_BUFFER_MEMORY_INFO_GENERATE_DAT_SYM 1
#define DMA_READ_MASTER_BUFFER_MEMORY_INFO_GENERATE_HEX 1
#define DMA_READ_MASTER_BUFFER_MEMORY_INFO_HAS_BYTE_LANE 0
#define DMA_READ_MASTER_BUFFER_MEMORY_INFO_HEX_INSTALL_DIR QPF_DIR
#define DMA_READ_MASTER_BUFFER_MEMORY_INFO_MEM_INIT_DATA_WIDTH 32
#define DMA_READ_MASTER_BUFFER_MEMORY_INFO_MEM_INIT_FILENAME soc_system_BUFFER

/*
 * Macros for device 'AUDIO', class 'altera_up_avalon_audio'
 * Path to the device is from the master group 'DMA_write_master'.
 * The macros are prefixed with 'DMA_WRITE_MASTER_AUDIO_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define DMA_WRITE_MASTER_AUDIO_COMPONENT_TYPE altera_up_avalon_audio
#define DMA_WRITE_MASTER_AUDIO_COMPONENT_NAME AUDIO
#define DMA_WRITE_MASTER_AUDIO_BASE 0x8860
#define DMA_WRITE_MASTER_AUDIO_SPAN 16
#define DMA_WRITE_MASTER_AUDIO_END 0x886f

/*
 * Macros for device 'BUTTONS', class 'altera_avalon_pio'
 * The macros are prefixed with 'BUTTONS_'.
 * The prefix is the slave descriptor.
 */
#define BUTTONS_COMPONENT_TYPE altera_avalon_pio
#define BUTTONS_COMPONENT_NAME BUTTONS
#define BUTTONS_BASE 0x8800
#define BUTTONS_SPAN 16
#define BUTTONS_END 0x880f
#define BUTTONS_IRQ 4
#define BUTTONS_BIT_CLEARING_EDGE_REGISTER 1
#define BUTTONS_BIT_MODIFYING_OUTPUT_REGISTER 0
#define BUTTONS_CAPTURE 1
#define BUTTONS_DATA_WIDTH 3
#define BUTTONS_DO_TEST_BENCH_WIRING 0
#define BUTTONS_DRIVEN_SIM_VALUE 0
#define BUTTONS_EDGE_TYPE FALLING
#define BUTTONS_FREQ 50000000
#define BUTTONS_HAS_IN 1
#define BUTTONS_HAS_OUT 0
#define BUTTONS_HAS_TRI 0
#define BUTTONS_IRQ_TYPE EDGE
#define BUTTONS_RESET_VALUE 0

/*
 * Macros for device 'SEVEN_SEGMENTS', class 'altera_avalon_pio'
 * The macros are prefixed with 'SEVEN_SEGMENTS_'.
 * The prefix is the slave descriptor.
 */
#define SEVEN_SEGMENTS_COMPONENT_TYPE altera_avalon_pio
#define SEVEN_SEGMENTS_COMPONENT_NAME SEVEN_SEGMENTS
#define SEVEN_SEGMENTS_BASE 0x8810
#define SEVEN_SEGMENTS_SPAN 16
#define SEVEN_SEGMENTS_END 0x881f
#define SEVEN_SEGMENTS_BIT_CLEARING_EDGE_REGISTER 0
#define SEVEN_SEGMENTS_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SEVEN_SEGMENTS_CAPTURE 0
#define SEVEN_SEGMENTS_DATA_WIDTH 28
#define SEVEN_SEGMENTS_DO_TEST_BENCH_WIRING 0
#define SEVEN_SEGMENTS_DRIVEN_SIM_VALUE 0
#define SEVEN_SEGMENTS_EDGE_TYPE NONE
#define SEVEN_SEGMENTS_FREQ 50000000
#define SEVEN_SEGMENTS_HAS_IN 0
#define SEVEN_SEGMENTS_HAS_OUT 1
#define SEVEN_SEGMENTS_HAS_TRI 0
#define SEVEN_SEGMENTS_IRQ_TYPE NONE
#define SEVEN_SEGMENTS_RESET_VALUE 0

/*
 * Macros for device 'TIMER', class 'altera_avalon_timer'
 * The macros are prefixed with 'TIMER_'.
 * The prefix is the slave descriptor.
 */
#define TIMER_COMPONENT_TYPE altera_avalon_timer
#define TIMER_COMPONENT_NAME TIMER
#define TIMER_BASE 0x8820
#define TIMER_SPAN 32
#define TIMER_END 0x883f
#define TIMER_IRQ 1
#define TIMER_ALWAYS_RUN 0
#define TIMER_COUNTER_SIZE 32
#define TIMER_FIXED_PERIOD 1
#define TIMER_FREQ 50000000
#define TIMER_LOAD_VALUE 24999999
#define TIMER_MULT 0.001
#define TIMER_PERIOD 500
#define TIMER_PERIOD_UNITS ms
#define TIMER_RESET_OUTPUT 0
#define TIMER_SNAPSHOT 1
#define TIMER_TICKS_PER_SEC 2
#define TIMER_TIMEOUT_PULSE_OUTPUT 0

/*
 * Macros for device 'JTAG_UART', class 'altera_avalon_jtag_uart'
 * The macros are prefixed with 'JTAG_UART_'.
 * The prefix is the slave descriptor.
 */
#define JTAG_UART_COMPONENT_TYPE altera_avalon_jtag_uart
#define JTAG_UART_COMPONENT_NAME JTAG_UART
#define JTAG_UART_BASE 0x8840
#define JTAG_UART_SPAN 8
#define JTAG_UART_END 0x8847
#define JTAG_UART_IRQ 2
#define JTAG_UART_READ_DEPTH 64
#define JTAG_UART_READ_THRESHOLD 8
#define JTAG_UART_WRITE_DEPTH 64
#define JTAG_UART_WRITE_THRESHOLD 8

/*
 * Macros for device 'AUDIO_CONFIG', class 'altera_up_avalon_audio_and_video_config'
 * The macros are prefixed with 'AUDIO_CONFIG_'.
 * The prefix is the slave descriptor.
 */
#define AUDIO_CONFIG_COMPONENT_TYPE altera_up_avalon_audio_and_video_config
#define AUDIO_CONFIG_COMPONENT_NAME AUDIO_CONFIG
#define AUDIO_CONFIG_BASE 0x8850
#define AUDIO_CONFIG_SPAN 16
#define AUDIO_CONFIG_END 0x885f

/*
 * Macros for device 'BUFFER', class 'altera_avalon_onchip_memory2'
 * The macros are prefixed with 'BUFFER_'.
 * The prefix is the slave descriptor.
 */
#define BUFFER_COMPONENT_TYPE altera_avalon_onchip_memory2
#define BUFFER_COMPONENT_NAME BUFFER
#define BUFFER_BASE 0x20000
#define BUFFER_SPAN 131072
#define BUFFER_END 0x3ffff
#define BUFFER_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define BUFFER_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define BUFFER_CONTENTS_INFO ""
#define BUFFER_DUAL_PORT 0
#define BUFFER_GUI_RAM_BLOCK_TYPE AUTO
#define BUFFER_INIT_CONTENTS_FILE soc_system_BUFFER
#define BUFFER_INIT_MEM_CONTENT 1
#define BUFFER_INSTANCE_ID NONE
#define BUFFER_NON_DEFAULT_INIT_FILE_ENABLED 0
#define BUFFER_RAM_BLOCK_TYPE AUTO
#define BUFFER_READ_DURING_WRITE_MODE DONT_CARE
#define BUFFER_SINGLE_CLOCK_OP 0
#define BUFFER_SIZE_MULTIPLE 1
#define BUFFER_SIZE_VALUE 131072
#define BUFFER_WRITABLE 1
#define BUFFER_MEMORY_INFO_DAT_SYM_INSTALL_DIR SIM_DIR
#define BUFFER_MEMORY_INFO_GENERATE_DAT_SYM 1
#define BUFFER_MEMORY_INFO_GENERATE_HEX 1
#define BUFFER_MEMORY_INFO_HAS_BYTE_LANE 0
#define BUFFER_MEMORY_INFO_HEX_INSTALL_DIR QPF_DIR
#define BUFFER_MEMORY_INFO_MEM_INIT_DATA_WIDTH 32
#define BUFFER_MEMORY_INFO_MEM_INIT_FILENAME soc_system_BUFFER


#endif /* _ALTERA_HPS_0_H_ */
