#ifndef _ALTERA_HPS_0_H_
#define _ALTERA_HPS_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file '../soc_system.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps_0' and devices
 * connected to the following masters:
 *   h2f_axi_master
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'BUTTONS', class 'altera_avalon_pio'
 * The macros are prefixed with 'BUTTONS_'.
 * The prefix is the slave descriptor.
 */
#define BUTTONS_COMPONENT_TYPE altera_avalon_pio
#define BUTTONS_COMPONENT_NAME BUTTONS
#define BUTTONS_BASE 0x8800
#define BUTTONS_SPAN 16
#define BUTTONS_END 0x880f
#define BUTTONS_IRQ 4
#define BUTTONS_BIT_CLEARING_EDGE_REGISTER 1
#define BUTTONS_BIT_MODIFYING_OUTPUT_REGISTER 0
#define BUTTONS_CAPTURE 1
#define BUTTONS_DATA_WIDTH 3
#define BUTTONS_DO_TEST_BENCH_WIRING 0
#define BUTTONS_DRIVEN_SIM_VALUE 0
#define BUTTONS_EDGE_TYPE FALLING
#define BUTTONS_FREQ 50000000
#define BUTTONS_HAS_IN 1
#define BUTTONS_HAS_OUT 0
#define BUTTONS_HAS_TRI 0
#define BUTTONS_IRQ_TYPE EDGE
#define BUTTONS_RESET_VALUE 0

/*
 * Macros for device 'SEVEN_SEGMENTS', class 'altera_avalon_pio'
 * The macros are prefixed with 'SEVEN_SEGMENTS_'.
 * The prefix is the slave descriptor.
 */
#define SEVEN_SEGMENTS_COMPONENT_TYPE altera_avalon_pio
#define SEVEN_SEGMENTS_COMPONENT_NAME SEVEN_SEGMENTS
#define SEVEN_SEGMENTS_BASE 0x8810
#define SEVEN_SEGMENTS_SPAN 16
#define SEVEN_SEGMENTS_END 0x881f
#define SEVEN_SEGMENTS_BIT_CLEARING_EDGE_REGISTER 0
#define SEVEN_SEGMENTS_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SEVEN_SEGMENTS_CAPTURE 0
#define SEVEN_SEGMENTS_DATA_WIDTH 28
#define SEVEN_SEGMENTS_DO_TEST_BENCH_WIRING 0
#define SEVEN_SEGMENTS_DRIVEN_SIM_VALUE 0
#define SEVEN_SEGMENTS_EDGE_TYPE NONE
#define SEVEN_SEGMENTS_FREQ 50000000
#define SEVEN_SEGMENTS_HAS_IN 0
#define SEVEN_SEGMENTS_HAS_OUT 1
#define SEVEN_SEGMENTS_HAS_TRI 0
#define SEVEN_SEGMENTS_IRQ_TYPE NONE
#define SEVEN_SEGMENTS_RESET_VALUE 0

/*
 * Macros for device 'TIMER', class 'altera_avalon_timer'
 * The macros are prefixed with 'TIMER_'.
 * The prefix is the slave descriptor.
 */
#define TIMER_COMPONENT_TYPE altera_avalon_timer
#define TIMER_COMPONENT_NAME TIMER
#define TIMER_BASE 0x8820
#define TIMER_SPAN 32
#define TIMER_END 0x883f
#define TIMER_IRQ 1
#define TIMER_ALWAYS_RUN 0
#define TIMER_COUNTER_SIZE 32
#define TIMER_FIXED_PERIOD 1
#define TIMER_FREQ 50000000
#define TIMER_LOAD_VALUE 24999999
#define TIMER_MULT 0.001
#define TIMER_PERIOD 500
#define TIMER_PERIOD_UNITS ms
#define TIMER_RESET_OUTPUT 0
#define TIMER_SNAPSHOT 1
#define TIMER_TICKS_PER_SEC 2
#define TIMER_TIMEOUT_PULSE_OUTPUT 0

/*
 * Macros for device 'JTAG_UART', class 'altera_avalon_jtag_uart'
 * The macros are prefixed with 'JTAG_UART_'.
 * The prefix is the slave descriptor.
 */
#define JTAG_UART_COMPONENT_TYPE altera_avalon_jtag_uart
#define JTAG_UART_COMPONENT_NAME JTAG_UART
#define JTAG_UART_BASE 0x8840
#define JTAG_UART_SPAN 8
#define JTAG_UART_END 0x8847
#define JTAG_UART_IRQ 2
#define JTAG_UART_READ_DEPTH 64
#define JTAG_UART_READ_THRESHOLD 8
#define JTAG_UART_WRITE_DEPTH 64
#define JTAG_UART_WRITE_THRESHOLD 8

/*
 * Macros for device 'AUDIO_CONFIG', class 'altera_up_avalon_audio_and_video_config'
 * The macros are prefixed with 'AUDIO_CONFIG_'.
 * The prefix is the slave descriptor.
 */
#define AUDIO_CONFIG_COMPONENT_TYPE altera_up_avalon_audio_and_video_config
#define AUDIO_CONFIG_COMPONENT_NAME AUDIO_CONFIG
#define AUDIO_CONFIG_BASE 0x8850
#define AUDIO_CONFIG_SPAN 16
#define AUDIO_CONFIG_END 0x885f

/*
 * Macros for device 'AUDIO', class 'altera_up_avalon_audio'
 * The macros are prefixed with 'AUDIO_'.
 * The prefix is the slave descriptor.
 */
#define AUDIO_COMPONENT_TYPE altera_up_avalon_audio
#define AUDIO_COMPONENT_NAME AUDIO
#define AUDIO_BASE 0x8860
#define AUDIO_SPAN 16
#define AUDIO_END 0x886f
#define AUDIO_IRQ 3


#endif /* _ALTERA_HPS_0_H_ */
